---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 2 with R 
  | STAT 301-2
author: "Alexis Sullivan"
pagetitle: "Self Evaluation L01 Alexis Sullivan"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Sullivan GitHub Link](https://github.com/stat301-3-2026-spring/l01-review-lexisullivan30)

:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

The following procedure can be followed to construct a supervised machine learning model:

1) Explore the outcome variable (assessing for missingness or class imbalances)
2) Transform the outcome variable
3) Split the dataset into training and testing data
4) Divide the training set into folds, if using resampling for the process
5) Use feature engineering to construct a complex recipe along with a baseline recipe
6) Specify the model types (ie. regression/classification, linear/tree-based)
7) Define model workflows (ie. add model specs and recipes)
8) Define hyperparamter tuning grids
9) Tune hyperparameter grids to workflows and folds
10) Evaluate highest-performing model types and identify ideal hyperparameter values
11) Fit the best model type to the entire training data set
12) Test the fitted model on the entire testing data set
13) Evaluate the performance of the final model in making predictions

:::


### Self Evaluation Question 1

::: {.callout-important icon="false"}

## Score 
4

**Explanation**

My solution was overall thorough and accurate. The steps could have been more concise,
but they are in the correct order and demonstrate a clear understanding of the model
building process. Also, I did not include the "Data collection" step as I presumed
the model buidling process would occur after collecting data, but this is not the
case.

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

In unsupervised learning, the model does not have a given target variable to supervise
the predictive process. Instead, the model must use the entirety of the unstructured data to 
extract patterns and information. In the supervised learning case, the model has a specific
target variable that guides the algorithm and structures the predictive process to answer
a clear objective.

:::

### Self Evaluation Question 2

::: {.callout-important icon="false"}

## Score 
4

**Explanation**

My original answer clearly indicates the primary difference between supervised and
unsupervised learning is the presence or absence of a specified target variable. My
answer also indicates that unsupervised learning is better at targeting relationships
and patterns among variables, while supervised learning uses the target variable to
predict outcomes on new observations.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

These models aim to understand a data set from input and output variables, and ultimately describe
the patterns and relationships of the variables. Parametric models are preferable for descriptive
models for these reasons because they intrinsically summarize statistical relationships.

:::

### Self Evaluation Question 3 Part A

::: {.callout-important icon="false"}

## Score 
5

**Explanation**

My original answer was quite long, but ultimately captures the idea that this model
type describes a characteristic present in the data.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

These models aim to provide explanations for the relationships represented in the data set,
and ultimately infer where relationships have statistical significance within a population.
These models might analyze whether relationships between variables are causal, or test
whether relationships between variables in a data set are generalizable to a population.
Parametric models are very useful for these types of models because of probability theory.

:::

### Self Evaluation Question 3 Part B

::: {.callout-important icon="false"}

## Score 
3

**Explanation**

My original answer was quite long, but ultimately captures the idea that this model
type can answer hypothesis-based research questions. After reading the solutions, it
is clear that this model is especially useful for answering causal questions. However,
my original answer does imply that these models depend on probability theory, but this
could be more specific. These models depend on underlying theoretical assumptions from
statistics.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

These models aim to create accurate predictions based on the data set, regardless of the
specifics of the modeling process. Parametric and non-parametric models are both critical
for these models because predictive models do not specifically require explanations for how
the variables are utilized to generate accurate predictions.

:::

### Self Evaluation Question 3 Part C

::: {.callout-important icon="false"}

## Score 
5

**Explanation**

My answer captures the primary idea that predictive models generate predictions of a 
target variable for new data.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

Mechanistic models have a known equation where the model assigns parametric values to
the functional form according to the predictor variables and training dataset. These
models make assumptions based on underlying mathematical theory, making them highly
interpretable. However, because this model type relies on a specified formula, the
models are not flexible to the datasets like an empirically driven model type.

:::

### Self Evaluation Question 4 Part A

::: {.callout-important icon="false"}

## Score 
3

**Explanation**

The explanation highlights important aspects of mechanistic models. Mainly, they rely
on mathematical assumptions, highly interpretable, and can be relatively inflexible. My
solution could have included that these models are computational fast and require fewer
observations, since this is implied by the fact that they follow a specific mathematical
process. I also did not include a specific example of a mechanistic model because this
was not written in the directions, but this could include logistic or linear regression.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirically driven models do not have a known equation that the model must leverage
to create predictions. These models use the observational data within the dataset, rather
than underlying mathematical theory and formulas, to generate predictions. These models
tend to be highly flexible to the specific observations in the dataset; however, they
are more difficult to interpret since there is no mathematical theory driving the
process.

:::

### Self Evaluation Question 4 Part B

::: {.callout-important icon="false"}

## Score 
2

**Explanation**

My solution could be more clear and concise to communicate the key ideas of empirically-driven
models. First, the models use observational data to capture patterns between the input
and output variables to generate predictions. These models do not have an underlying process
that can be rooted in mathematical theory. Because of their reliance on observations and
nuanced patterns, these models require more data observations and longer computation time.
I also did not provide any examples of these models because the directions did not specify
to include that.

**Updated Solution**

Empirically driven models are non-parametric, so there is not a known equation or
mathematical theory guiding the modeling process. Instead, these models capture patterns
between outcome and input variables to generate predictions. These models require more
data points and a longer computation time to extract these patterns. Ultimately, since
they do not rely on mathematical assumptions, these models are more flexible to the
observations in the dataset. Some empirically driven models include Random Tree or
K-Nearest Neighbors.

:::


#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Parametric models tend to correlate with mechanistic models because these models inherently
estimate parameter values for the given mathematical formulas. Nonparametric models tend
to correlate with empirically driven models because these models do not depend on a 
specified mathematical formula, and therefore do not inherently generate parameter values
based on a functional form.

:::

### Self Evaluation Question 4 Part C

::: {.callout-important icon="false"}

## Score 
4

**Explanation**

My solution could be more clear and concise to state that mechanistic models are
parametric and empirically-driven models are non-parametric.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are easier to interpret because of the mathematical theory which
clearly guides the creation of the models. For example, a linear models will have clear
parameter values given to each predictor variable to generate predictions, while a tree-based 
model uses loose connections between observations to generate predictions.

:::

### Self Evaluation Question 4 Part D

::: {.callout-important icon="false"}

## Score 
4

**Explanation**

My solution could be more clear by stating that empirically-driven models can be difficult
or impossible to interpret because there is no mathematical form informing the process. However,
my original answer illustrates the idea that mechanistic models are easier to interpret
since there is specific formulas and theory driving the process.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible than mechanistic models because they inherently
rely on the specific observations held within a dataset to create predictions. A mechanistic
model has a specified formula guiding the model's prediction, which could simply not match
the relationships of the predictor variables in that particular dataset. An empirically
driven model does not possess the same constraints from a formula, and merely uses the
relationships present in the dataset, making it much more reliant on the dataset to
inform its construction.

:::

### Self Evaluation Question 4 Part E

::: {.callout-important icon="false"}

## Score 
5

**Explanation**

My solution clearly implies that empricially-driven models are more flexible because
they are heavily-dependent on the specific observations of the dataset and are not
constrained by a mathematical formula.

:::


#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Variance describes how predicted outcomes vary based on the datasets supplied to the models, while
bias describes the errors from real-world data collection or imbalances. More flexible models, like
the empircally driven models, tend to have a higher variance due to their reliance on the specific
observations in the dataset. For example, the predictions generated by a tree-model will differ
based on the observations of that dataset, and are less likely to be reproducible. Conversely, the
predictions generated by a linear model will vary less based on the observations of the datset because
the model follows underlying mathematical theory. However, more flexible models tend to have a lower
bias because they can adjust to fit the dataset's observations. Mechanistic models must follow
assumptions about the dataset and the functional form, leading to more bias. 

:::

### Self Evaluation Question 4 Part F

::: {.callout-important icon="false"}

## Score 
2

**Explanation**

My solution could be more clear in its applications of bias and variance by each model
type. As the sample solution clarifies, mechanistic models have a specific frame of
model mechanisms that can fit to certain data points. As a result, there is low variance
because the model mechanisms do not shift based on the data observations. Further, there
is high bias because the model mechanisms cannot fit every data point precisely. Conversely,
empirically-driven models have a flexible frame of model mechanisms to conform to the
data observations. This means high variance because the model inherently changes according
to the data points, but low bias since most data points can fit within the frame precisely.

**Updated Solution**

Variance describes how predicted outcomes vary based on the datasets supplied to the models, 
while bias describes the errors from real-world data collection or imbalances. Mechanistic
models have a restricted framework of model mechanisms to fit the dataset. This means low
variance because these model mechanisms will not conform to the observations; however, this
means higher bias since the model mechanisms will not perfectly capture the data observations
within its framework. Empirically-driven models have a flexible framework of model mechanisms
to fit the dataset. This means high variance because the framework will be transformed based
on the specific observations in the data; however, this leads to low bias because the model
mechanisms can mold to fit the data points precisely.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression machine learning problems generate numeric predictions, while classification
machine learning problems generate categorical (ie. class) predictions.

:::

### Self Evaluation Question 5

::: {.callout-important icon="false"}

## Score 
5

**Explanation**
My answer very clearly communicates the correct answer.

:::


### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the target variable is always useful to resolve any class imbalances. Stratification
ensures that data at all levels of the outcome variable are properly represented within the training
data and folds. It alleviates class imbalances in classification problems or numeric skews in regression
problems.

:::

### Self Evaluation Question 6

::: {.callout-important icon="false"}

## Score 
2

**Explanation**

While my solution discusses how stratification reduces errors introduced by imbalances in
the outcome variable, it could be more clear. I was unsure how stratification relates to
the training, testing, and folding processes. After reading the solution, I understand
that stratification is critical in ensuring that both the training and testing data have
ample observations of different levels of the outcome variable. This ensures that the
models have adequate data to train on, and the testing data is complex enough to properly
evaluate the model.

**Updated Solution**

Stratifying by the target variable reduces imbalances or skews in the dataset by ensuring
that the distribution of the outcome variable is similar across both the testing and
training dataset. Ensuring the target data is evenly represented in its distribution among
both datasets leads to better model fitting and rigorous model testing. Without similar balances 
of the target variable in the training and testing data, the models could struggle with overfitting 
or underfitting. 

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation helps estimate model parameters more accurately by averaging the
true population parameters across models built from folds in the original training dataset.
Essentially, the V-fold cross validation process constructs multiple models from different
versions of the training dataset to inform a single model based on the means of each model.
This reduces the bias introduced by the randomness of the initial split, lowering the
RMSE of the models because the population parameter should be more accurately measured.

Also, the resampling procedure alleviate overfitting issues. Because of the nature of
resampling, which uses the average of numerous models trained and tested on distinct folds,
the models are exposed to more variability and will perform better against test data.

:::

### Self Evaluation Question 7

::: {.callout-important icon="false"}

## Score 
5

**Explanation**
My answer very clearly communicates the correct answer.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Boostrap resampling tends to be more useful on small datasets. V-fold cross validation
with few observations can generate too much variance because folds are selected without
replacement. Boostrap resampling uses replacement to create folds, which helps when
there are a smaller amount of observations, and therefore statistically information, 
to base predictions on.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Certain models rely on parameter values which can be adjusted according to the predictive
power of the variables in the dataset. For example, tree models must be supplied with a specific
value for the number of trees the model will use to generate predictions. Naturally, some level
of the number of trees will create the most effecient and powerful model, but this must
be estimated through expsoure to training data and comparison to other levels of the variable.
Using a tuning process, these parameter values can be optimized to increase the accuracy of 
predictions by the models. Because tuning parameters must be specified before the models can 
be evaluated on testing data, by finding the best values of the hyperparameters through training and 
resampling, the models' predictive power can be maximized.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

Root-Mean Square Error (RMSE) calculates the accuracy of numeric estimates by comparing
the square-root of the mean difference of observed and predicted values after being squared.
This amplifies the impacts of large differences from observed and predicted values because of
the squaring of the differences before finding the square-root of the sum.

Mean Absolute Error (MAE) calculates the accuracy of numeric estimates by comparing the
mean of the absolute value of differences between observed and predicted values. Without
the squaring of residuals, this metric places smaller emphasis on large differences than
an RMSE estimate. However, this metric is quite easy to estimate and interpret.

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy calculates the proportion of correct predictions out of every prediction. This
metric is the total number of true positives and negatives divided by all predictions,
which gives the number of accurate predictions made out of all predictions made by the model.

Precision calculates the proportion positive predictions, meaning the model must specify a
base class or the positive class. Based on the base class, the precision metric finds the
proportion of true predicted positives over all positives in the dataset. This metric offers
a measurement of how frequently the model generates false positives.

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential problem because the question searches for a relationship between
two variables: number of service calls and customer churn. This is looking to explain a relationship
between two variables, not generate a prediction for the value of one variable.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a predictive problems because the question aims to predict the customer's behavior
based on a set of variables. The problem requires a model that will use previously observed
data to inform future predictions, not try to determine relationships among variables to
answer a hypothesis.

:::

